version: "2.4"

services:

  eureka-server:
    build: ./eurika
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-service
    networks:
      - biblio-network

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "9999:9999"
    depends_on:
      - eureka-server  
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
  
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - biblio-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - biblio-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - biblio-network

  notification-service:
    build: ./notification
    container_name: notification-service
    depends_on:
      - eureka-server
      - kafka
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - biblio-network

  user-service:
    build: ./user
    container_name: user-service
    depends_on:
      eureka-server
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - biblio-network

  book-service:
    build: ./book
    container_name: book-service
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=book-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - biblio-network

  emprunt-service:
    build: ./emprunter
    container_name: emprunt-service
    depends_on:
      - eureka-server
      - user-service
      - book-service
    environment:
      - SPRING_APPLICATION_NAME=emprunt-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - biblio-network

networks:
  biblio-network:
    driver: bridge
